# This is a set of bugbot commands for issues and merge requests - setting any of the
# bugbot::foo labels will trigger gitlab-triage to run with this ruleset (well, the
# one we have on the main branch at the time)
#
# Note that for adding labels via gitlab-triage, the label must first be created in the project.


################################################################################
# Issues
################################################################################

.remind-stale-issue: &remind-stale-issue
  name: "Remind of stale issues"
  conditions:
    date:
      attribute: updated_at
      condition: older_than
      interval_type: months
      interval: 12
    state: opened
    forbidden_labels:
    - "stale"
  limits:
    oldest: 100
  actions:
    labels: "stale"
    comment: |
      Hi {{author}}! Can you confirm if this issue is still relevant?
      If so, please remove the ~"stale" label and comment on this issue.

      Without an update, this issue will be closed in 1 month.

.close-stale-issue: &close-stale-issue
  name: "Close stale issues"
  conditions:
    date:
      attribute: updated_at
      condition: older_than
      interval_type: months
      interval: 1
    state: opened
    labels:
    - "stale"
  limits:
    oldest: 100
  actions:
    comment: |
      Hi {{author}}! Since this stale issue has not been updated, it’s being closed.

      If this issue is still relevant, please reopen, remove the ~"stale" label and add a comment.
    status: "close"

################################################################################
# Merge requests
################################################################################

.remind-stale-mr: &remind-stale-mr
  name: "Remind of stale MRs"
  conditions:
    date:
      attribute: updated_at
      condition: older_than
      interval_type: months
      interval: 3
    state: opened
    forbidden_labels:
    - "stale"
  limits:
    oldest: 100
  actions:
    labels: "stale"
    comment: |
      Hi {{author}}! Can you confirm if you’re still working on this merge request?
      If so, please remove the ~"stale" label and comment on this issue.

      Without an update, this merge request will be closed in 1 month.

.close-stale-mr: &close-stale-mr
  name: "Close stale MRs"
  conditions:
    date:
      attribute: updated_at
      condition: older_than
      interval_type: months
      interval: 1
    state: opened
    labels:
    - "stale"
  limits:
    oldest: 100
  actions:
    comment: |
      Hi {{author}}! Since this stale merge request has not been updated, it’s being closed.

      If this merge request is still relevant, please reopen, remove the ~"stale" label and add a comment.
    status: "close"

################################################################################
# Miscellaneous
################################################################################

.too-exotic: &too-exotic
  name: "Close as too exotic"
  conditions:
    labels:
      - "bugbot::too-exotic"
  actions:
    remove_labels:
      - "bugbot::too-exotic"
    comment: |
      Hi. Thanks for filing this issue/merge request. We think this keyboard layout is too exotic
      to be shipped as part of the default xkeyboard-config keymaps. Layouts added to
      the distribution means we have to maintain these layouts for years and decades into
      the future and we avoid having to do so for layouts that we expect have a tiny number of
      users.

      As a general rule, we will add layouts that are part of official standards but not
      experimental layouts. If this is the case here, please re-open with a comment.

      Please install it as a custom layout instead, we have
      [instructions for Xorg](https://who-t.blogspot.com/2021/02/a-pre-supplied-custom-keyboard-layout.html)
      and [instructions for Wayland](https://xkbcommon.github.io/libxkbcommon/doc/current/md_doc_user_configuration.html).
    status: "close"

################################################################################
# Rules
################################################################################

resource_rules:
  issues:
    rules:
      - *too-exotic
      - *remind-stale-issue
      - *close-stale-issue
  merge_requests:
    rules:
      - *too-exotic
      - *remind-stale-mr
      - *close-stale-mr
